systems:
    - "libsysdrawable"
    - "libsyswindow"
    - "libsysmovable"
    - "libsysclickable"
    - "libsysanimate"
    - "libsysmoving"
    - "libsysshooter"
    - "libsyscollision"
    - "libsysnetworked"
    - "libsysspawner"
entities:
    window:
        components:
            window:
                title: "r-type"
                width: 1900
                height: 1080
                max_fps: 60
                icon: "ressources/ui/icon.png"
                sound: "ressources/sound/main.ogg"
    background_1:
        components:
            sprite:
                texture: "ressources/ui/bg.png"
            moving:
                start_x: 0
                dest_x: -1920
                duration: 15
                loop: true
            transform:
                x: 0
    background_2:
        components:
            sprite:
                texture: "ressources/ui/bg.png"
            moving:
                start_x: 1920
                dest_x: 0
                duration: 15
                loop: true
            transform:
                x: 1920
